use_frameworks!

platform :ios, '8.0'

target 'XBaseUIKit_Example' do
  pod 'XBaseUIKit', :path => '../'

  target 'XBaseUIKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
